SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

CREATE DATABASE IF NOT EXISTS `logistica` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `logistica`;
DROP TABLE IF EXISTS `almacen`;
CREATE TABLE IF NOT EXISTS `almacen`
(
  `ID` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `NOMBRE` varchar(45) COLLATE utf8_spanish_ci NOT NULL,
  `LUGAR` varchar(11) COLLATE utf8_spanish_ci NOT NULL
) 
ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

INSERT INTO `almacen` (`ID`,`NOMBRE`, `LUGAR`) VALUES
(1, 'SEDE CENTRAL', 'MADRID'),
(2, 'ALMACEN GETAFE', 'GETAFE'),
(3, 'ALMACEN LEGANES', 'LEGANES'),
(4, 'ALMACEN VILLAVERDE', 'MADRID'),
(5, 'ALMACEN BURGOS', 'BURGOS');

DROP TABLE IF EXISTS `productos`;
CREATE TABLE IF NOT EXISTS `productos`
(
  `ID` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `NOMBRE` varchar(45) COLLATE utf8_spanish_ci NOT NULL,
  `ESTRELLA` tinyint(1) DEFAULT NULL,
  `ALMACEN_ID` int(11) NOT NULL
  ) 
ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;

INSERT INTO `productos` (`ID`,`NOMBRE`, `ESTRELLA`, `ALMACEN_ID`) VALUES
(12341, 'CAMISETA', NULL, 2),
(12342, 'CAMISETA', NULL, 2),
(12343, 'CAMISETA', NULL, 2),
(12344, 'CAMISETA', NULL, 2),
(12345, 'CAMISETA', NULL, 2),
(23451, 'JERSEY', NULL, 4),
(23452, 'JERSEY', NULL, 4),
(23453, 'JERSEY', NULL, 4);

ALTER TABLE `productos` ADD KEY `fk_vendedor` (`ALMACEN_ID`);

ALTER TABLE `productos` ADD CONSTRAINT `fk_vendedor` FOREIGN KEY (`ALMACEN_ID`) REFERENCES `almacen` (`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;
COMMIT;